export const NOTIFICATIONSSENDSYSTEM = 'notificationsSendSystem';
export const USERSROLESANDPERMISSIONSPERMISSIONSRECEIVEALLFROMSERVICE = 'usersRolesAndPermissionsPermissionsReceiveAllFromService';
export const USERSROLESANDPERMISSIONSPERMISSIONSREQUESTFROMALL = 'usersRolesAndPermissionsPermissionsRequestFromAll';
export const USERSROLESANDPERMISSIONSROLESCHANGED = 'usersRolesAndPermissionsRolesChanged';
export const USERSROLESANDPERMISSIONSROLESREQUEST = 'usersRolesAndPermissionsRolesRequest';

