export const KKEVENTADMINSUCCESSREALMROLECREATE = 'KK.EVENT.ADMIN.*.SUCCESS.REALM_ROLE.CREATE';
export const KKEVENTADMINSUCCESSUSERCREATE = 'KK.EVENT.ADMIN.*.SUCCESS.USER.CREATE';
export const KKEVENTADMINSUCCESSUSERUPDATE = 'KK.EVENT.ADMIN.*.SUCCESS.USER.UPDATE';
export const KKEVENTCLIENTAPPREALMSOMERESULTSOMECLIENTREGISTRATION = 'KK.EVENT.CLIENT.APPREALM.SOMERESULT.SOMECLIENT.REGISTRATION';
export const NOTIFICATIONSSENDSYSTEM = 'notifications_sendSystem';
export const NOTIFICATIONSSENDUSERWELCOME = 'notifications_sendUserWelcome';
export const USERSROLESANDPERMISSIONSPERMISSIONSINCOMINGALLFROMONESERVICE = 'usersRolesAndPermissions_permissionsIncomingAllFromOneService';
export const USERSROLESANDPERMISSIONSPERMISSIONSREQUESTFROMALLSERVICES = 'usersRolesAndPermissions_permissionsRequestFromAllServices';
export const USERSROLESANDPERMISSIONSROLESALLUPDATED = 'usersRolesAndPermissions_rolesAllUpdated';
export const USERSROLESANDPERMISSIONSROLESREQUESTALL = 'usersRolesAndPermissions_rolesRequestAll';

